Request a DOI for each ETD submission
ndlib/sipity pull request #1264
Opened 2021-02-26 17:15 UTC by laritakr

1. Add DOI attribute to ETD work types with default value "To be assigned"

CURATE-248

2021-05-13 17:19 UTC, msuhovec reviewed
OK, I am missing something. I see the TaskWriter module, and how it will build the JOB file with the designated taskname in the todo list. Where is this called, and what is that task name for doi minting?

2021-05-13 17:46 UTC, msuhovec requested changes
Could you change the task name from doi-request to start-doi-request?  All of the initial workflow tasks (so far) begin with 'start'. That's what the initial task for doi-minting is named at present.

2021-05-13 18:27 UTC, laritakr commented
> OK, I am missing something. I see the TaskWriter module, and how it will build the JOB file with the designated taskname in the todo list. Where is this called, and what is that task name for doi minting?

This is just a WIP PR because I'm going over some questions tomorrow.... more changes will be coming.

2021-05-27 15:47 UTC, msuhovec approved these changes

2021-05-28 13:08 UTC, merged